### ISSUE TITLE
Rename files that differ only in captalisation

### ISSUE THREAD

**Issue by aaronsnoswell** [Kinovarobotics/kinova-movo#19]
The kinova-movo repo contains some files in directories that differ only in capitalisation. This causes issues when using the git repo from an NTFS filesystem, which doesn't care about filename capitalisation.

In particular, the files in the folder https://github.com/Kinovarobotics/kinova-movo/tree/master/movo_common/movo_description/meshes/sensors/collision are a problem for me.

Would you be able to rename one of these files to a different name?

Thank you,

**Comment by martine1406** [comment]
done
