### ISSUE TITLE
Kinect power cable rubbing internally

### ISSUE THREAD

**Issue by aaronsnoswell** [Kinovarobotics/kinova-movo#21]
Hi Kinova,

I was having a look inside the top of our MOVO today (front 'head' skin panel removed) and noticed that the Kinect power cable has some serious mechanical wear. See below.

![MOVO Kinect Power Cable](https://user-images.githubusercontent.com/967771/37636485-3755d476-2c4e-11e8-9c6f-3c9a1c8bcce8.jpg)

You can't see it in the above photo, but the Kinect cable is actually worn through to the point where the internal metal sheath is visible.

I believe this rubbing is happening when the MOVO torso linear actuator is used, but we've hardly used this actuator, so I'm not sure if it was exercised lots before shipping to us?

**Comment by aaronsnoswell** [comment]
I did some more investigation and confirmed that the linear actuator is responsible. After raising the torso, sometimes when you lower it the Kinect cable gets pinched (see below photos). The culprit is the lip on the top of the linear actuator support.

![Pinched cable](https://user-images.githubusercontent.com/967771/37636873-4313b114-2c50-11e8-8638-50bf52cbaba6.jpg)

![Frayed cable](https://user-images.githubusercontent.com/967771/37636877-4776ecee-2c50-11e8-8730-d0d5c8dfeea5.jpg)

We've fixed this on our MOVO using some electrical tape and the addition of two internal zip ties. I suggest this is fixed in future MOVO builds :)

![Fixed cable](https://user-images.githubusercontent.com/967771/37636878-4be460ea-2c50-11e8-8417-a96c63b490bf.jpg)

**Comment by martine1406** [comment]
Hi @aaronsnoswell

Thank you for reporting this problem. I confirm that we have a solution (protective box) that will be available for the next movos we ship. We checked, and it is possible to retrofit this box on current movo units that were manufactured without. I'll ask if we can get you one of these box along with instructions on how to install it. 

Thanks
Martine

**Comment by aaronsnoswell** [comment]
Awesome. Looking forward to receiving it. Thanks.

**Comment by brandonjdehart** [comment]
Sounds good to me! Thanks, Martine!
