### ISSUE TITLE
Rename `movo_jtas.py` to `movo_arm_jtas.py`?

### ISSUE THREAD

**Issue by tttor** [Kinovarobotics/kinova-movo#25]
Should `movo_jtas.py` be renamed to `movo_arm_jtas.py`?
If so, this will provide naming consistency with other files under [`movo_jtas` dir](https://github.com/Kinovarobotics/kinova-movo/tree/master/movo_common/movo_ros/src/movo_jtas).

**Comment by martine1406** [comment]
Hi @tttor 

This could be an interesting idea. Just requiring a little bit on configuration in the different files calling to movo_jtas.py. Do you want to modify the naming on your side and submit a pull request?
