### ISSUE TITLE
gmapping.launch

### ISSUE THREAD

**Issue by stefie10** [Kinovarobotics/kinova-movo#32]
I'm trying to follow the instructions here: https://github.com/Kinovarobotics/kinova-movo/wiki/How-Tos#creating-a-map-with-real-robot

And in particular this instruction: "Launch navigation: o roslaunch movo_navigation_apps gmapping.launch."

However I can't find gmapping.launch in kinova-movo.  I also searched for this file on the movo1, movo2, and Google, and can't find it.

**Comment by martine1406** [comment]
Done. Thank you for letting us know.
