### ISSUE TITLE
Commanding the Fingers Individually

### ISSUE THREAD

**Issue by stefie10** [Kinovarobotics/kinova-movo#33]
Hi,

I am able to open and close the grippers via the SimpleActionClient.  However this only gives access to a single number to control the finger position.  While it's nice to have that API, I was wondering if there was in addition an API to control each fingers individually?  I see the finger joint state topic, but was wondering if there was a topic to set each finger joint position and/or velocity individually?  For example, I want to be able to make a "V" for victory sign, or a one-finger pointing gesture, or strum a ukulele. 

Sorry if I missed it in the docs... I ran rostopic list | grep gripper and looked at all the topics and didn't see any way to set individual finger positions.  I was able to do this with the jaco api before... 

Thanks.

**Comment by martine1406** [comment]
Hi @stefie10 

The Kinova C++ API allows you to control each of the fingers individually. Ultimately, to communicate with Kinova arms, the movo ROS package has to use the C++ API, and more specifically functions [SendBasicTrajectory](https://github.com/Kinovarobotics/kinova-movo/blob/master/movo_common/movo_ros/src/movo_joint_interface/kinova_api_wrapper.py#L196) or [SendAdvanceTrajectory](https://github.com/Kinovarobotics/kinova-movo/blob/master/movo_common/movo_ros/src/movo_joint_interface/kinova_api_wrapper.py#L194). Indeed, the TrajectoryPoint has one field for each finger. Right now, as you noticed, the "higher-level" functions are not configured to send commands to individual fingers. But you can certainly write your own node to send commands to each finger individually, eventually calling to SendBasicTrajectory or SendAdvanceTrajectory. You can see how it is currently done with the [update_cartesian_vel_cmd](https://github.com/Kinovarobotics/kinova-movo/blob/92bd4dd01c6bb4520cbf7db99004f377168e0c46/movo_common/movo_ros/src/movo_joint_interface/kinova_api_wrapper.py) function (i.e. same command sent to all three fingers)

I hope this helps
Martine
