### ISSUE TITLE
Cartographer support

### ISSUE THREAD

**Issue by stefie10** [Kinovarobotics/kinova-movo#35]
Hi,

Is there a plan to add support for Google Cartographer?  I have heard it's better than gmapper but have no direct experience either way. 

https://github.com/googlecartographer/cartographer

**Comment by martine1406** [comment]
Hi @stefie10 

We always welcome your suggestions :-) Let's see if this is a common need. If you want to try it on your end and share your experience with the community, you are more than welcome

Thank you!
Martine

**Comment by brandonjdehart** [comment]
It would also be good to support Hector SLAM. That would enable users to choose to use one (or more) of the three main SLAM options that are available right now in ROS: http://wiki.ros.org/hector_slam, http://wiki.ros.org/cartographer, and http://wiki.ros.org/gmapping.

**Comment by martine1406** [comment]
agreed. We'll keep that in mind. In the meantime, if you guys have time to try these different mapping options on your end, let us know.
