### ISSUE TITLE
apt-get update/apt-get upgrade

### ISSUE THREAD

**Issue by stefie10** [Kinovarobotics/kinova-movo#37]
Is it okay to run apt-get update/apt-get upgrade on the movo?  If I run that on movo1/movo2 to get the security updates (and generally, keep running it), will it break anything?

**Comment by martine1406** [comment]
Hi @stefie10 

Thanks for asking. Go ahead. We do not see any problem with running apt-get update/apt-get upgrade on movo1 and movo2. No danger to screw up the ros package. 

Cheers
Martine
