### ISSUE TITLE
move_base_action_client.py: `movo_move_base`, instead of `move_base`?

### ISSUE THREAD

**Issue by tttor** [Kinovarobotics/kinova-movo#4]
Hi All:

In [this line](https://github.com/Kinovarobotics/kinova-movo/blob/8936d75a691562672543dee2c0df43d8d53f70c6/movo_common/movo_ros/src/movo_action_clients/move_base_action_client.py#L66),
should not it be `movo_move_base`, instead of `move_base`?
```
self.move_base_client = actionlib.SimpleActionClient("/movo_move_base", MoveBaseAction)
```
Using `movo_base` there and launching [`demo_extra.launch`](https://github.com/Kinovarobotics/kinova-movo/blob/master/movo_simulation/movo_gazebo_demo/launch/demo_extras.launch), we got:
```
[ERROR] [WallTime: 1516248125.612894] [326.658000] Could not connect to action server
Traceback (most recent call last):
  File "/home/tor/catkin-ws/src/kinova-movo/movo_simulation/movo_gazebo_demo/scripts/demo.py", line 360, in <module>
    move_base = MoveBaseActionClient(sim=True)
  File "/home/tor/catkin-ws/src/kinova-movo/movo_common/movo_ros/src/movo_action_clients/move_base_action_client.py", line 76, in __init__
    self._shutdown()
AttributeError: 'MoveBaseActionClient' object has no attribute '_shutdown'
```
What do you think?

Thank you,
tor

PS: this is using:
kinova-movo-master: Latest commit 8936d75
Indigo, trusty

**Comment by martine1406** [comment]
You are right. I will correct that now. Thanks
