### ISSUE TITLE
Movo arms end-effectors twist values

### ISSUE THREAD

**Issue by andrewhou1** [Kinovarobotics/kinova-movo#46]
Hi,

So we're currently trying to read the Jaco arms' end-effectors velocities (both linear x,y and z and angular as x, y, z as well). We noticed that in the kinova-ros package, there is a custom message type called PoseVelocity which has exactly the fields we need. The documentation for kinova-ros mentions a way to send PoseVelocity message commands to Movo, but we're wondering if there is some way to read the PoseVelocity of the end effectors? Is there a topic, service, launch file, or anything we can use to constantly read and publish the PoseVelocity of the Jaco arms onto some topic?

Thanks!

**Comment by martine1406** [comment]
Hi. 

For of all, kinova-ros and movo packages are two separate packages. You might not have the same functionalities in both. 
You have the option to send Cartesian velocity commands to the movo arms by publishing on the /movo/right_arm/cartesian_vel_cmd topic
To send Cartesian position command, the current way is to use MoveIt. 

Unfortunately, I do not think there is a publisher defined to directly provide you the arm's Cartesian positions in movo (like the one you have in kinova-ros). You can either try to implement such a publisher (it would ultimately call to the GetCartesianCommand function from the Kinova API. This function will need to be added to [kinova_api_wrapper.py](https://github.com/Kinovarobotics/kinova-movo/blob/92bd4dd01c6bb4520cbf7db99004f377168e0c46/movo_common/movo_ros/src/movo_joint_interface/kinova_api_wrapper.py). The other option I see would be to use tf to get the transform between the base_frame and end_effector frame on each arm. 

I hope this helps
Martine
