### ISSUE TITLE
 Kinova moveit_core CMake Error when using ubunut 16.04

### ISSUE THREAD

**Issue by mambawockeez** [Kinovarobotics/kinova-movo#54]
Im using ubuntu 16.04 to work on a project using kinova arms. and after cloning all the files, when i catkin_make it, it show error like this. And i already adding add_compile_options(-std=c++11) in every cmakelist.txt in kinova folder. And here is my error screenshot.
![screenshot from 2018-10-31 14-13-01](https://user-images.githubusercontent.com/26910282/47809383-1b7d8f80-dd17-11e8-8c9e-0429855588f1.png)
 Could anyone help me with this issue please! Really appreciate your help!

**Comment by martine1406** [comment]
Not related to this repo
