### ISSUE TITLE
Removing Jaco Arm

### ISSUE THREAD

**Issue by djrakita** [Kinovarobotics/kinova-movo#57]
Hi, we are trying to remove one of the Jaco arms from the Movo platform.  I followed the instructions on this page: https://kinovarobotics.github.io/kinova-movo/Tasks/t_kinova_arms_uninstall.html ; however, when I get to step 3, the robot arm does not budge.  I was feeling around to see how the arm was still attached, and felt a screw on the underside of the base.  Is it possible for the arm to be screwed in from UNDER the base, and not just on the top like step 2 indicates?  If this is the case, it would seem like we'd have to disassemble most of the robot to get access to this screw.  I thought it was worth checking here before doing anything close to that drastic.  Any help would be much appreciated, thanks!

**Comment by alexvannobel** [comment]
Hi @djrakita !

For any hardware-related issue, we invite you to directly contact our support team at support@kinova.ca, as we specified in the movo-beta-program group here : https://github.com/orgs/Kinovarobotics/teams/movo-beta-program/discussions/47

We try as much as possible to have the software issues on Github and the hardware issues by email. 

Thanks for your comprehension!

Alex
