### ISSUE TITLE
Movo quickly powers off after being turned on

### ISSUE THREAD

**Issue by ericrosenbrown** [Kinovarobotics/kinova-movo#76]
Hello,

We are currently having an issue where after hitting hitting the power button on movo to turn it on, the movo boots up, but then dies after being on for about 30 seconds. The back button starts by beeping yellow (which indicates booting up), but then switches to red (indicating booting down), and then shuts off. When I connect a monitor directly to the movo, I see linux bootup, but the robot powers off shortly after. The movo is plugged in, and appears to have 75-100% battery. Is there any suggestions for how to figure out the issue? Thanks!

**Comment by ericrosenbrown** [comment]
It seems like the NUC is not having issues, and specifically that the power from the base of the robot just cuts out shortly after booting. Is there any suggested debugging methods for figuring out how to resolve this power issue?

**Comment by ericrosenbrown** [comment]
Where can we find a data sheet for the board specs for the base of the robot? we are trying to figure out if there is a blown fuse causing the power issue, but we can't find a data sheet for the board online.

**Comment by belgiumkansas** [comment]
have you tried cycling the battery switch in the base of the unit and starting off battery power?

**Comment by ericrosenbrown** [comment]
That solved our problem, thank you so much!!
